name: main
on:
  - pull_request
  - push
jobs:
  main:
    matrix:
      rust:
        - stable
        - beta
        - nightly
    name: ${{matrix.rust}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{matrix.rust}}
          components: rustfmt, clippy
      - run: |
          rustup
      - run: rustup --version
      - run: rustc -vV

      - run: cargo clippy -- -W clippy::pedantic
      - run: cargo fmt --all -- --check
      - run: cargo test
        #      - run: cargo install cargo-tarpaulin && cargo tarpaulin --out Xml
        #      - uses: codecov/codecov-action@v1
        #    strategy:

