name: Default on Windows
on:
  - pull_request
  - push
  - workflow_dispatch
jobs:
  main:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7
      - run: rustup --version
      - run: rustc -vV

      - run: cargo clippy -- --deny clippy::pedantic
      - run: cargo fmt --all -- --check
      - run: cargo test

